
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yarinaosi_development

test:
  <<: *default
  database: yarinaosi_test

production:
  <<: *default
  database: yarinaosi_production
  username: yarinaosi
  password: <%= ENV['YARINAOSI_DATABASE_PASSWORD'] %>
